# roles/replicator/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_replicator_namespace }}"
    - path: "{{ openio_replicator_sysconfig_dir }}/{{ openio_replicator_servicename }}"
    - path: "/var/log/oio/sds/{{ openio_replicator_namespace }}/{{ openio_replicator_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0770"
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "replicator.conf.j2"
      dest: "{{ openio_replicator_sysconfig_dir }}/\
        {{ openio_replicator_servicename }}/replicator.conf"
    - src: "gridinit_replicator.conf.j2"
      dest: "{{ openio_replicator_gridinit_dir }}/{{ openio_replicator_gridinit_file_prefix }}\
        {{ openio_replicator_servicename }}.conf"
  register: _replicator_conf

- name: "restart replicator to apply the new configuration"
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{ openio_replicator_namespace }}-{{ openio_replicator_servicename }}
  register: _restart_replicator
  when:
    - _replicator_conf is changed
    - not openio_replicator_provision_only
  tags: configure

- block:
    - name: "Ensure replicator is started"
      command: gridinit_cmd start {{ openio_replicator_namespace }}-{{ openio_replicator_servicename }}
      register: _start_replicator
      changed_when: '"Success" in _start_replicator.stdout'
      when:
        - not openio_replicator_provision_only
        - _restart_replicator is skipped
      tags: configure
  when: openio_bootstrap | d(false)
...
